version: '3'

vars:
  BINARY_NAME: server
  CMD_PATH: ./cmd/server
  # Kubernetes
  KUBECTL: kubectl
  K8S_NAMESPACE: tiny-bitly
  K8S_DIR: k8s
  K8S_JOBS_DIR: k8s/jobs
  K8S_DEPLOYMENT: tiny-bitly
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  COMMIT:
    sh: git rev-parse HEAD 2>/dev/null || echo "unknown"
  BUILD_TIME:
    sh: date -u +%Y-%m-%dT%H:%M:%SZ

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the production binary with version info
    cmds:
      - echo "Building {{.BINARY_NAME}} with version {{.VERSION}}..."
      - 'go build -ldflags "-X tiny-bitly/internal/version.Version={{.VERSION}} -X tiny-bitly/internal/version.Commit={{.COMMIT}} -X tiny-bitly/internal/version.BuildTime={{.BUILD_TIME}}" -o bin/{{.BINARY_NAME}} {{.CMD_PATH}}'
      - echo "Binary built at bin/{{.BINARY_NAME}}"

  start:
    desc: Run the server (uses API_PORT env var, defaults to 8080)
    vars:
      PORT: "8080"
    cmds:
      - API_PORT={{.PORT}} go run {{.CMD_PATH}}/main.go

  test:
    desc: Run all tests
    cmds:
      - go test -v ./...

  test-coverage:
    desc: Run tests with coverage
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"

  test-load:
    desc: 'Run load test against the API. Example: task load-test ARGS="-users=100 -duration=60s"'
    vars:
      ARGS: "-users=100 -duration=60s -user-interval=2s"
    cmds:
      - go run ./cmd/test_load/main.go {{.ARGS}}

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf bin/
      - rm -f coverage.out coverage.html
      - echo "Cleaned build artifacts"

  db:
    desc: Access the Postgres database in Docker
    cmds:
      - docker exec -it tiny-bitly-postgres-1 psql -U admin -d tiny-bitly
      - \c tiny-bitly

  version:
    desc: Show current version info
    cmds:
      - echo "Version={{.VERSION}}"
      - echo "Commit={{.COMMIT}}"
      - echo "BuildTime={{.BUILD_TIME}}"

  migrate-build:
    desc: Build the migration tool
    cmds:
      - echo "Building migrate tool..."
      - go build -o bin/migrate ./cmd/migrate
      - echo "Binary built at bin/migrate"

  migrate:
    desc: Run database migrations up
    deps: [migrate-build]
    cmds:
      - ./bin/migrate -command=up

  migrate-force:
    desc: "Force migration version (use to fix dirty state). Usage: task migrate-force VERSION=1"
    deps: [migrate-build]
    cmds:
      - ./bin/migrate -command=force -version={{.VERSION}}

  migrate-version:
    desc: Show current migration version
    deps: [migrate-build]
    cmds:
      - ./bin/migrate -command=version

  load-test-data:
    desc: Load lots of test URL records into the database
    cmds:
      - go run ./cmd/load_test_data/main.go

  k8s:build-push:
    desc: Build and push Docker image to GCR (requires gcloud auth and docker)
    vars:
      PROJECT_ID:
        sh: gcloud config get-value project 2>/dev/null || echo "tiny-bitly"
      IMAGE_NAME: gcr.io/{{.PROJECT_ID}}/tiny-bitly
      IMAGE_TAG: latest
    cmds:
      - echo "Building Docker image {{.IMAGE_NAME}}:{{.IMAGE_TAG}}..."
      - docker buildx build --platform linux/amd64 -t {{.IMAGE_NAME}}:{{.IMAGE_TAG}} --push .
      - echo "Image pushed successfully"

  k8s:context:
    desc: Show current kubectl context
    cmds:
      - '{{.KUBECTL}} config current-context'
      
  k8s:deploy:
    desc: Apply manifests then restart + wait for rollout (does NOT run migrations)
    cmds:
      - '{{.KUBECTL}} apply -f {{.K8S_DIR}}/'
      - '{{.KUBECTL}} -n {{.K8S_NAMESPACE}} rollout restart deployment/{{.K8S_DEPLOYMENT}}'
      - '{{.KUBECTL}} -n {{.K8S_NAMESPACE}} rollout status deployment/{{.K8S_DEPLOYMENT}}'

  k8s:migrate:
    desc: Create a new migration Job (uses generateName, so use kubectl create)
    cmds:
      - '{{.KUBECTL}} create -f {{.K8S_JOBS_DIR}}/migration-job.yaml'

  k8s:migrate:logs:
    desc: Tail logs for the most recently created migration Job
    cmds:
      - |
        set -eu
        JOB="$({{.KUBECTL}} -n {{.K8S_NAMESPACE}} get jobs --sort-by=.metadata.creationTimestamp -o name | tail -1)"
        echo "Tailing logs for ${JOB} in namespace {{.K8S_NAMESPACE}}..."
        {{.KUBECTL}} -n {{.K8S_NAMESPACE}} logs "${JOB}" --tail=200

  k8s:status:
    desc: Show tiny-bitly k8s resources (deployments/pods/services/ingress/jobs)
    cmds:
      - '{{.KUBECTL}} -n {{.K8S_NAMESPACE}} get deploy,pods,svc,ingress,jobs'
