version: '3'

vars:
  BINARY_NAME: server
  CMD_PATH: ./cmd/server
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  COMMIT:
    sh: git rev-parse HEAD 2>/dev/null || echo "unknown"
  BUILD_TIME:
    sh: date -u +%Y-%m-%dT%H:%M:%SZ

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the production binary with version info
    cmds:
      - echo "Building {{.BINARY_NAME}} with version {{.VERSION}}..."
      - 'go build -ldflags "-X tiny-bitly/internal/version.Version={{.VERSION}} -X tiny-bitly/internal/version.Commit={{.COMMIT}} -X tiny-bitly/internal/version.BuildTime={{.BUILD_TIME}}" -o bin/{{.BINARY_NAME}} {{.CMD_PATH}}'
      - echo "Binary built at bin/{{.BINARY_NAME}}"

  build-dev:
    desc: Build the development binary (no version injection)
    cmds:
      - echo "Building {{.BINARY_NAME}} for development..."
      - go build -o bin/{{.BINARY_NAME}} {{.CMD_PATH}}
      - echo "Binary built at bin/{{.BINARY_NAME}}"

  run:
    desc: Build and run the server
    deps: [build-dev]
    cmds:
      - ./bin/{{.BINARY_NAME}}

  test:
    desc: Run all tests
    cmds:
      - go test -v ./...

  test-coverage:
    desc: Run tests with coverage
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf bin/
      - rm -f coverage.out coverage.html
      - echo "Cleaned build artifacts"

  version:
    desc: Show current version info
    cmds:
      - echo "Version={{.VERSION}}"
      - echo "Commit={{.COMMIT}}"
      - echo "BuildTime={{.BUILD_TIME}}"
